version: "3.8"

services:
  budgets-db:
    volumes:
      - budget-storage-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${BUDGETS_DB_PASSWORD}
    ports:
      - ${BUDGETS_DB_PORT}:5432
    networks:
      global-hub-net:

  notes-db:
    volumes:
      - notes-storage-volume:/data/db
    ports:
      - ${NOTES_DB_PORT}:27017
    networks:
      global-hub-net:

  notifications-db:
    volumes:
      - notifications-storage-volume:/data/db
    ports:
      - ${NOTIFICATIONS_DB_PORT}:27017
    networks:
      global-hub-net:

  identity-db:
    environment:
      - MSSQL_SA_PASSWORD=${IDENTITY_DB_PASSWORD}
      - ACCEPT_EULA=Y
    volumes:
      - identity-storage-volume:/var/opt/mssql
    ports:
      - ${IDENTITY_DB_PORT}:1433
    networks:
      global-hub-net:

  projects-db:
    environment:
      - MSSQL_SA_PASSWORD=${PROJECTS_DB_PASSWORD}
      - ACCEPT_EULA=Y
    volumes:
      - projects-storage-volume:/var/opt/mssql
    ports:
      - ${PROJECTS_DB_PORT}:1433
    networks:
      global-hub-net:
  
  event-bus:
    ports:
      - ${RABBIT_MQ_WEB_UI_PORT}:15672
      - ${RABBIT_MQ_COMMUNICATION_PORT}:5672
    volumes:
      - event-bus-storage-volume:/var/lib/rabbitmq
    networks:
      global-hub-net:

  elasticsearch:
    volumes:
      - elasticsearch-storage-volume:/usr/share/elasticsearch/data
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    networks:
      global-hub-net:

  budgets-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=DOCKER_COMPOSE_DEMO
      - BUDGETS_SERVICE_STORAGE_CONNECTION_STRING=${BUDGETS_SERVICE_STORAGE_CONNECTION_STRING}
      - IDENTITY_SERVICE_URL=${IDENTITY_SERVICE_URL}
      - LOG_STORAGE=${ELASTIC_SEARCH_CONNECTION_STRING}
      - EVENT_BUS_CONNECTION_STRING=${EVENT_BUS_CONNECTION_STRING}
    ports:
      - ${BUDGETS_SERVICE_PORT}:80
    depends_on:
      - budgets-db
      - event-bus
    networks:
      global-hub-net:

  notes-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=DOCKER_COMPOSE_DEMO
      - NOTES_SERVICE_STORAGE_CONNECTION_STRING=${NOTES_SERVICE_STORAGE_CONNECTION_STRING}
      - IDENTITY_SERVICE_URL=${IDENTITY_SERVICE_URL}
      - LOG_STORAGE=${ELASTIC_SEARCH_CONNECTION_STRING}
      - EVENT_BUS_CONNECTION_STRING=${EVENT_BUS_CONNECTION_STRING}
    ports:
      - ${NOTES_SERVICE_PORT}:80
    depends_on:
      - notes-db
      - event-bus
    networks:
      global-hub-net:

  projects-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=DOCKER_COMPOSE_DEMO
      - PROJECTS_DB_CONNECTIONN_STRING=${PROJECTS_DB_CONNECTION_STRING}
      - IDENTITY_SERVICE_URL=${IDENTITY_SERVICE_URL}
      - LOG_STORAGE=${ELASTIC_SEARCH_CONNECTION_STRING}
      - EVENT_BUS_CONNECTION_STRING=${EVENT_BUS_CONNECTION_STRING}
    ports:
      - ${PROJECTS_SERVICE_PORT}:80
    depends_on:
      projects-db:
        condition: service_healthy
      event-bus:
        condition: service_healthy
    networks:
      global-hub-net:

  identity-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=DOCKER_COMPOSE_DEMO
      - REINITIALIZE_IDENTITY_RESOURCES=${REINITIALIZE_IDENTITY_RESOURCES}
      - IDENTITY_DB_CONNECTION_STRING=${IDENTITY_DB_CONNECTION_STRING}
      - OPERATIONAL_DB_CONNECTION_STRING=${OPERATIONAL_DB_CONNECTION_STRING}
      - CONFIGURATION_DB_CONNECTION_STRING=${CONFIGURATION_DB_CONNECTION_STRING}
      - IdentityServer__Clients__0__RedirectUris__0__RedirectUri=${REDIRECT_URI}
      - IdentityServer__Clients__0__PostLogoutRedirectUris__0__PostLogoutRedirectUri=${POST_LOGOUT_REDIRECT_URI}
      - LOG_STORAGE=${ELASTIC_SEARCH_CONNECTION_STRING}
    ports:
      - ${IDENTITY_SERVICE_PORT}:80
    depends_on:
      identity-db:
        condition: service_healthy
    networks:
      global-hub-net:
  
  notifications-service:
    ports:
      - ${NOTIFICATIONS_SERVICE_PORT}:80
    environment:
      - ASPNETCORE_ENVIRONMENT=DOCKER_COMPOSE_DEMO
      - NOTIFICATIONS_DB_CONNECTION_STRING=${NOTIFICATIONS_DB_CONNECTION_STRING}
      - IDENTITY_SERVICE_URL=${IDENTITY_SERVICE_URL}
      - LOG_STORAGE=${ELASTIC_SEARCH_CONNECTION_STRING}
      - EVENT_BUS_CONNECTION_STRING=${EVENT_BUS_CONNECTION_STRING}
    depends_on:
      - notifications-db
      - event-bus
    networks:
      global-hub-net:
  
  full-text-search-service:
    ports:
      - ${FULL_TEXT_SEARCH_SERVICE_PORT}:80
    environment:
      - ASPNETCORE_ENVIRONMENT=DOCKER_COMPOSE_DEMO
      - ELASTIC_SEARCH_URL=${ELASTIC_SEARCH_CONNECTION_STRING}
      - IDENTITY_SERVICE_URL=${IDENTITY_SERVICE_URL}
      - LOG_STORAGE=${ELASTIC_SEARCH_CONNECTION_STRING}
      - EVENT_BUS_CONNECTION_STRING=${EVENT_BUS_CONNECTION_STRING}
    depends_on:
      notifications-db:
        condition: service_started
      event-bus:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      global-hub-net:

  api-gateway-service:
    ports:
      - ${API_GATEWAY_PORT}:80
    environment:
      - ASPNETCORE_ENVIRONMENT=DOCKER_COMPOSE_DEMO
      - IDENTITY_SERVICE_URL=${IDENTITY_SERVICE_URL}
      - LOG_STORAGE=${ELASTIC_SEARCH_CONNECTION_STRING}
      - GlobalConfiguration__BaseUrl=${GlobalConfiguration__BaseUrl}
    depends_on:
      - notes-service
      - budgets-service
      - projects-service
      - identity-service
      - full-text-search-service
      - notifications-service
    networks:
      global-hub-net:

  global-hub-client:
    environment:
      - NODE_ENV=production
      - API_GATEWAY_URL=${API_GATEWAY_URL}
      - CLIENT_ID=global-hub-local
      - REDIRECT_URI=${REDIRECT_URI}
      - POST_LOGOUT_REDIRECT_URI=${POST_LOGOUT_REDIRECT_URI}
    ports:
      - ${CLIENT_APP_PORT}:80
    depends_on:
      - api-gateway-service
    networks:
      global-hub-net:
