version: "3.8"
name: "gh-demo"

services:
  budgets-db:
    container_name: dc-budgets-db
    image: postgres:16

  notes-db:
    container_name: dc-notes-db
    image: mongo:7

  notifications-db:
    container_name: dc-notifications-db
    image: mongo:7

  identity-db:
    container_name: dc-identity-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U "sa" -P "$$MSSQL_SA_PASSWORD" -Q "Select 1"
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 15s

  projects-db:
    container_name: dc-projects-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U "sa" -P "$$MSSQL_SA_PASSWORD" -Q "Select 1"
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 15s

  event-bus:
    container_name: dc-event-bus
    image: rabbitmq:3.12.13-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 15s

  elasticsearch:
    container_name: dc-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    image: elasticsearch:8.12.2
    healthcheck:
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200/
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 15s

  identity-service:
    container_name: dc-identity-service
    build:
      context: .
      dockerfile: ./Services/IdentityService/IdentityService.Presentation/Dockerfile
    image: gh-identity-service:latest

  budgets-service:
    container_name: dc-budgets-service
    build:
      context: .
      dockerfile: ./Services/BudgetService/BudgetsService.Web/Dockerfile
    image: gh-budgets-service:latest

  notes-service:
    container_name: dc-notes-service
    build:
      context: .
      dockerfile: ./Services/NotesService/Dockerfile
    image: gh-notes-service:latest

  projects-service:
    container_name: dc-projects-service
    build:
      context: .
      dockerfile: ./Services/ProjectService/ProjectService.Presentation/Dockerfile
    image: gh-projects-service:latest
  
  notifications-service:
    container_name: dc-notifications-service
    build:
      context: .
      dockerfile: ./Services/NotificationService.API/Dockerfile
    image: gh-notifications-service:latest

  full-text-search-service:
    container_name: dc-full-text-search-service
    build:
      context: .
      dockerfile: ./Services/FullTextSearchService/FullTextSearchApi/Dockerfile
    image: gh-full-text-search-service:latest

  api-gateway-service:
    container_name: dc-api-gateway-service
    build:
      context: .
      dockerfile: ./Services/ApiGateway/Dockerfile
    image: gh-api-gateway-service:latest

  global-hub-client:
    container_name: dc-global-hub-client
    image: gh-client:latest
    build:
      context: ../ClientApp
      dockerfile: ../ClientApp/Dockerfile

volumes:
  notes-storage-volume:
  budget-storage-volume:
  identity-storage-volume:
  projects-storage-volume:
  notifications-storage-volume:
  elasticsearch-storage-volume:
  event-bus-storage-volume:

networks:
  global-hub-net:
