// Global using directives

global using System.Security.Claims;
global using Common.Constants;
global using Common.EventBus.Enums;
global using Common.EventBus.Messages.FullTextSearchModels.Notes;
global using Common.ExceptionHandling;
global using Common.Exceptions;
global using Common.Extensions;
global using Common.Logging;
global using Common.Services;
global using Common.Services.Abstract;
global using MassTransit;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.IdentityModel.Logging;
global using Microsoft.OpenApi.Models;
global using MongoDB.Bson;
global using MongoDB.Bson.Serialization.Attributes;
global using MongoDB.Driver;
global using NotesService.Constants;
global using NotesService.Data.DbContext;
global using NotesService.Data.DbContext.Interfaces;
global using NotesService.Data.Repositories;
global using NotesService.Data.Repositories.Interfaces;
global using NotesService.Dtos;
global using NotesService.Entities;
global using Serilog;
